version: "3"
services:
  aws-cli-container:
    build: ./aws-cli
    container_name: awscli-container
    volumes:
      - ./workdir:/workdir
    env_file:
      - ./aws-cli/.env
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
    tty: true
